### ISSUE TITLE
MITM fails on Windows 8.1 N: Unknown signature type requested: SHA256

### ISSUE THREAD

**Issue by ganskef** [ganskef/LittleProxy-mitm#18]
On a fresh installed Windows 8.1 N with a recent Java the Man-In-The-Middle is disabled at startup:

<pre>
C:\Users\frank>java -version
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) Client VM (build 25.91-b14, mixed mode, sharing)

2016-04-29 22:07:10,588 WARN  [main] proxy.McProxy - MITM disabled, could not be initialized.
org.littleshoot.proxy.mitm.RootCertificateException: Errors during assembling root CA.
	at org.littleshoot.proxy.mitm.HostNameMitmManager.<init>(HostNameMitmManager.java:28)
	at de.ganskef.mocuishle.proxy.McProxy.createMitmManager(McProxy.java:105)
	at de.ganskef.mocuishle.proxy.McProxy.start(McProxy.java:85)
	at de.ganskef.mocuishle.McProxyMain.main(McProxyMain.java:48)
Caused by: java.lang.IllegalArgumentException: Unknown signature type requested: SHA256
	at org.bouncycastle.operator.DefaultSignatureAlgorithmIdentifierFinder.generate(Unknown Source)
	at org.bouncycastle.operator.DefaultSignatureAlgorithmIdentifierFinder.find(Unknown Source)
	at org.bouncycastle.operator.jcajce.JcaContentSignerBuilder.<init>(Unknown Source)
	at org.littleshoot.proxy.mitm.CertificateHelper.signCertificate(CertificateHelper.java:256)
	at org.littleshoot.proxy.mitm.CertificateHelper.createRootCertificate(CertificateHelper.java:183)
	at org.littleshoot.proxy.mitm.BouncyCastleSslEngineSource.initializeKeyStore(BouncyCastleSslEngineSource.java:261)
	at org.littleshoot.proxy.mitm.BouncyCastleSslEngineSource.<init>(BouncyCastleSslEngineSource.java:114)
	at org.littleshoot.proxy.mitm.BouncyCastleSslEngineSource.<init>(BouncyCastleSslEngineSource.java:137)
	at org.littleshoot.proxy.mitm.HostNameMitmManager.<init>(HostNameMitmManager.java:25)
	... 3 more
</pre>

**Comment by ganskef** [comment]
With Windows 8.1 N from https://java.com/download a 32-bit JVM was installed by default. This detects an error introduced with commit 4aced85. The missed bracket is fixed now.

**Every certificate creation is failing on a 32-bit JVM with littleproxy-mitm v1.1.0-beta2b!**
