### ISSUE TITLE
java.lang.NoClassDefFoundError: org/bouncycastle/util/Encodable

### ISSUE THREAD

**Issue by BullyWiiPlaza** [ganskef/LittleProxy-mitm#34]
If I add the maven dependency

```
<dependency>
	<groupId>com.github.ganskef</groupId>
	<artifactId>littleproxy-mitm</artifactId>
	<version>1.1.0</version>
</dependency>
```

I still get a `NoClassDefFoundError` due to `Encodable` missing from `Bouncycastle`:

```
import org.junit.Test;
import org.littleshoot.proxy.HttpProxyServer;
import org.littleshoot.proxy.impl.DefaultHttpProxyServer;
import org.littleshoot.proxy.mitm.CertificateSniffingMitmManager;
import org.littleshoot.proxy.mitm.RootCertificateException;

public class TestManInTheMiddle
{
	@Test
	public void test() throws RootCertificateException
	{
		HttpProxyServer server =
				DefaultHttpProxyServer.bootstrap()
						.withPort(9090) // for both HTTP and HTTPS
						.withManInTheMiddle(new CertificateSniffingMitmManager())
						.start();
	}
}
```

```
java.lang.NoClassDefFoundError: org/bouncycastle/util/Encodable

	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.littleshoot.proxy.mitm.CertificateHelper.createRootCertificate(CertificateHelper.java:164)
	at org.littleshoot.proxy.mitm.BouncyCastleSslEngineSource.initializeKeyStore(BouncyCastleSslEngineSource.java:219)
	at org.littleshoot.proxy.mitm.BouncyCastleSslEngineSource.<init>(BouncyCastleSslEngineSource.java:111)
	at org.littleshoot.proxy.mitm.BouncyCastleSslEngineSource.<init>(BouncyCastleSslEngineSource.java:134)
	at org.littleshoot.proxy.mitm.CertificateSniffingMitmManager.<init>(CertificateSniffingMitmManager.java:34)
	at org.littleshoot.proxy.mitm.CertificateSniffingMitmManager.<init>(CertificateSniffingMitmManager.java:28)
	at TestManInTheMiddle.test(TestManInTheMiddle.java:14)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:305)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:365)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:330)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:78)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:328)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:65)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:292)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:305)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:412)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.ClassNotFoundException: org.bouncycastle.util.Encodable
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 44 more
```

Adding a dependency for `Bouncycastle` does not help:

```
<dependency>
	<groupId>org.bouncycastle</groupId>
	<artifactId>bcprov-jdk15</artifactId>
	<version>1.46</version>
</dependency>
```

Why is this not included by default so the code can be ran? How to do it? I'm on `Windows 10`.

**Comment by BullyWiiPlaza** [comment]
Nevermind, it works fine on a fresh project:

![image](https://user-images.githubusercontent.com/7620135/52738558-2ced5d80-2fcf-11e9-9cd6-68c7946ac1ea.png)

Note that all of these are imported just by `littleproxy-mitm`.
