### ISSUE TITLE
ittleProxy-mitm on android.

### ISSUE THREAD

**Issue by Anatame** [ganskef/LittleProxy-mitm#42]
I'm trying to run LittleProxy-mitm on android with the code:
```
 val server = DefaultHttpProxyServer.bootstrap()
            .withAddress(InetSocketAddress("127.0.0.1",  8100))
            .withManInTheMiddle(CertificateSniffingMitmManager())
            .start() but the app crashes with this error.
```

    java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/commons/io/IOUtils;

Full error: 

-   2022-04-26 14:03:01.828 3581-3581/com.anatame.localproxy E/AndroidRuntime: FATAL EXCEPTION: main
-       Process: com.anatame.localproxy, PID: 3581
-       java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/commons/io/IOUtils;
-           at org.littleshoot.proxy.mitm.CertificateHelper.createSubjectKeyIdentifier(CertificateHelper.java:204)
-           at org.littleshoot.proxy.mitm.CertificateHelper.createRootCertificate(CertificateHelper.java:167)
-           at org.littleshoot.proxy.mitm.BouncyCastleSslEngineSource.initializeKeyStore(BouncyCastleSslEngineSource.java:219)
-           at org.littleshoot.proxy.mitm.BouncyCastleSslEngineSource.<init>(BouncyCastleSslEngineSource.java:111)
-           at org.littleshoot.proxy.mitm.BouncyCastleSslEngineSource.<init>(BouncyCastleSslEngineSource.java:134)
-           at org.littleshoot.proxy.mitm.CertificateSniffingMitmManager.<init>(CertificateSniffingMitmManager.java:34)
-           at com.anatame.localproxy.MainActivity.onCreate(MainActivity.kt:18)
-           at android.app.Activity.performCreate(Activity.java:7893)
-           at android.app.Activity.performCreate(Activity.java:7880)
-           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
-           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3286)
-           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3460)
-           at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
-           at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
-           at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
-           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2047)
-           at android.os.Handler.dispatchMessage(Handler.java:107)
-           at android.os.Looper.loop(Looper.java:224)
-           at android.app.ActivityThread.main(ActivityThread.java:7592)
-           at java.lang.reflect.Method.invoke(Native Method)
-           at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
-           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
-        Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.commons.io.IOUtils" on path: DexPathList[[zip file "/data/app/com.anatame.localproxy-ZzekusIPuY-QWAB0xTPD7Q==/base.apk"],nativeLibraryDirectories=[/data/app/com.anatame.localproxy-ZzekusIPuY-QWAB0xTPD7Q==/lib/arm64, /system/lib64, /system/product/lib64]]
-           at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:230)
-           at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
-           at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
-           at org.littleshoot.proxy.mitm.CertificateHelper.createSubjectKeyIdentifier(CertificateHelper.java:204) 
-           at org.littleshoot.proxy.mitm.CertificateHelper.createRootCertificate(CertificateHelper.java:167) 
-           at org.littleshoot.proxy.mitm.BouncyCastleSslEngineSource.initializeKeyStore(BouncyCastleSslEngineSource.java:219) 
-           at org.littleshoot.proxy.mitm.BouncyCastleSslEngineSource.<init>(BouncyCastleSslEngineSource.java:111) 
-           at org.littleshoot.proxy.mitm.BouncyCastleSslEngineSource.<init>(BouncyCastleSslEngineSource.java:134) 
-           at org.littleshoot.proxy.mitm.CertificateSniffingMitmManager.<init>(CertificateSniffingMitmManager.java:34) 
-           at com.anatame.localproxy.MainActivity.onCreate(MainActivity.kt:18) 
-           at android.app.Activity.performCreate(Activity.java:7893) 
-           at android.app.Activity.performCreate(Activity.java:7880) 
-           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307) 
-           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3286) 
-           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3460) 
-           at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
-           at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
-           at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
-           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2047) 
-           at android.os.Handler.dispatchMessage(Handler.java:107) 
-           at android.os.Looper.loop(Looper.java:224) 
-           at android.app.ActivityThread.main(ActivityThread.java:7592) 
-           at java.lang.reflect.Method.invoke(Native Method) 
-           at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539) 
-           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950) 
-

**Comment by AltaOfficial** [comment]
You have to import commons.io

implementation("commons-io:commons-io:2.4")
